### PR TITLE
Fixed findCustomerByEmail Method

### LINKED ISSUE #6: Existing Customer not found by E-Mail
If an existing customer email is used to login e.g. abcd@wika.com (which already exists in the magento customer database) it won't found any customer data by email.

Looks like website relevance (multistore) is not reflected correctly. Maybe also for non-multistore not working correctly.

### PR DESCRIPTION
**Pull request by WIKAWebmaster**
@MasterZydra please check and merge if okay. 
Will Fix #6

### CODE REVIEW

**Comment by MasterZydra** [comment]
Hi @WIKAWebmaster, Thanks. I will take a look on Monday and apply the changes.

File: Helper/Data.php [hunk 1]
```diff
@@ -25,6 +25,8 @@ public function __construct(
         private \WikaGroup\AzureB2cSSO\Model\UserFactory $userFactory,
         private \WikaGroup\AzureB2cSSO\Model\ResourceModel\User $userRes,
         private \WikaGroup\AzureB2cSSO\Model\ResourceModel\User\CollectionFactory $userCollFactory,
+        // Mage2 Store
+        private \Magento\Store\Model\StoreManagerInterface $storemanager,
```
Comment (MasterZydra) [inline Helper/Data.php]: Store manager is already in constructor (line 18)

The property `customerCollFactory` is unused in this case. It can be removed from constructor.

File: Helper/Data.php [hunk 2]
```diff
@@ -184,10 +186,8 @@ public function findCustomerByOauthId(string $oauthId): ?Customer
...
     public function findCustomerByEmail(string $email): ?Customer
     {
-        $customerColl = $this->customerCollFactory->create()->addFieldToFilter('email', $email);
-        if ($customerColl->count() !== 1) {
-            return null;
-        }
-        return $customerColl->getFirstItem();
+      $websiteID = $this->storemanager->getStore()->getWebsiteId();
+      $customer = $this->customerFactory->create()->setWebsiteId($websiteID)->loadByEmail($email);
+        return $customer;
```
Comment (MasterZydra) [inline Helper/Data.php]: The signature of the functions returns a customer or null. So here a check if the customers id is null should be added.
